/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Avatar = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "avatar.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type RichText = {
  _type: "richText";
  eyebrow?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  anchor?: string;
};

export type Cta = {
  _type: "cta";
  heading?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  anchor?: string;
};

export type Faq = {
  _type: "faq";
  eyebrow?: string;
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
  anchor?: string;
};

export type TestimonialGrid = {
  _type: "testimonialGrid";
  eyebrow?: string;
  heading?: string;
  testimonials?: Array<{
    quote?: string;
    name?: string;
    role?: string;
    avatar?: Avatar;
    _type: "testimonial";
    _key: string;
  }>;
  anchor?: string;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading?: string;
  emphasis?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  anchor?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TestimonialGrid)
    | ({
        _key: string;
      } & Faq)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & RichText)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Avatar
  | RichText
  | Cta
  | Faq
  | TestimonialGrid
  | Hero
  | Link
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    description,    blocks[]{      ...,      _type == "hero" => { image {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }} },      _type == "testimonialGrid" => { testimonials[]{ ..., avatar {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }} } }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  blocks: Array<
    | {
        _key: string;
        _type: "cta";
        heading?: string;
        body?: string;
        actions?: Array<
          {
            _key: string;
          } & Link
        >;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "faq";
        eyebrow?: string;
        heading?: string;
        items?: Array<{
          question?: string;
          answer?: string;
          _type: "faqItem";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "hero";
        eyebrow?: string;
        heading?: string;
        emphasis?: string;
        body?: string;
        actions?: Array<
          {
            _key: string;
          } & Link
        >;
        image: {
          alt: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "richText";
        eyebrow?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "testimonialGrid";
        eyebrow?: string;
        heading?: string;
        testimonials: Array<{
          quote?: string;
          name?: string;
          role?: string;
          avatar: {
            alt: null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
          _type: "testimonial";
          _key: string;
        }> | null;
        anchor?: string;
      }
  > | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    description,\n    blocks[]{\n      ...,\n      _type == "hero" => { image {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n} },\n      _type == "testimonialGrid" => { testimonials[]{ ..., avatar {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n} } }\n    }\n  }\n': PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
