/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Avatar = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "avatar.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type RichText = {
  _type: "richText";
  eyebrow?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  anchor?: string;
};

export type Cta = {
  _type: "cta";
  heading?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  anchor?: string;
};

export type Faq = {
  _type: "faq";
  eyebrow?: string;
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
  anchor?: string;
};

export type TestimonialGrid = {
  _type: "testimonialGrid";
  eyebrow?: string;
  heading?: string;
  testimonials?: Array<{
    quote?: string;
    name?: string;
    role?: string;
    avatar?: Avatar;
    _type: "testimonial";
    _key: string;
  }>;
  anchor?: string;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading?: string;
  emphasis?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  anchor?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PageReference | PostReference;
  language?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: string;
  publishedAt?: string;
  tags?: Array<string>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  noindex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  description?: string;
  editorNote?: string;
  noindex?: boolean;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TestimonialGrid)
    | ({
        _key: string;
      } & Faq)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & RichText)
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Avatar
  | RichText
  | Cta
  | Faq
  | TestimonialGrid
  | Hero
  | Link
  | TranslationMetadata
  | InternationalizedArrayReference
  | PageReference
  | PostReference
  | InternationalizedArrayReferenceValue
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug && language == $language][0]{    _id,    _updatedAt,    language,    "slug": slug.current,    title,    description,    noindex,    "translations":   *[_type == "translation.metadata" && references(^._id)][0].translations[]{    language,    "slug": value->slug.current,    "noindex": value->noindex  }[defined(slug)],    blocks[]{      ...,      _type == "hero" => { image {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }} },      _type == "testimonialGrid" => { testimonials[]{ ..., avatar {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }} } }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  language: string | null;
  slug: string | null;
  title: string | null;
  description: string | null;
  noindex: boolean | null;
  translations: Array<{
    language: string | null;
    slug: string;
    noindex: boolean | null;
  }> | null;
  blocks: Array<
    | {
        _key: string;
        _type: "cta";
        heading?: string;
        body?: string;
        actions?: Array<
          {
            _key: string;
          } & Link
        >;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "faq";
        eyebrow?: string;
        heading?: string;
        items?: Array<{
          question?: string;
          answer?: string;
          _type: "faqItem";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "hero";
        eyebrow?: string;
        heading?: string;
        emphasis?: string;
        body?: string;
        actions?: Array<
          {
            _key: string;
          } & Link
        >;
        image: {
          alt: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "richText";
        eyebrow?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "testimonialGrid";
        eyebrow?: string;
        heading?: string;
        testimonials: Array<{
          quote?: string;
          name?: string;
          role?: string;
          avatar: {
            alt: null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
          _type: "testimonial";
          _key: string;
        }> | null;
        anchor?: string;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PAGE_PARAMS_QUERY
// Query: *[_type == "page" && defined(slug.current) && defined(language)]{    language,    "slug": slug.current  }
export type PAGE_PARAMS_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type == "page" && defined(slug.current) && defined(language) && noindex != true]{    language,    "slug": slug.current,    _updatedAt,    "translations":   *[_type == "translation.metadata" && references(^._id)][0].translations[]{    language,    "slug": value->slug.current,    "noindex": value->noindex  }[defined(slug)]  }
export type SITEMAP_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
  _updatedAt: string;
  translations: Array<{
    language: string | null;
    slug: string;
    noindex: boolean | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug && language == $language][0]{    _id,    _updatedAt,    language,    "slug": slug.current,    title,    excerpt,    author,    publishedAt,    tags,    noindex,    coverImage {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }},    body,    "translations":   *[_type == "translation.metadata" && references(^._id)][0].translations[]{    language,    "slug": value->slug.current,    "noindex": value->noindex  }[defined(slug)]  }
export type POST_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  language: string | null;
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  author: string | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  noindex: boolean | null;
  coverImage: {
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  translations: Array<{
    language: string | null;
    slug: string;
    noindex: boolean | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_INDEX_QUERY
// Query: *[_type == "post" && language == $language && defined(slug.current) && noindex != true]    | order(publishedAt desc){    _id,    "slug": slug.current,    title,    excerpt,    author,    publishedAt,    tags,    coverImage {  alt,  crop,  hotspot,  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }}  }
export type POST_INDEX_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  author: string | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  coverImage: {
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_PARAMS_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(language)]{    language,    "slug": slug.current  }
export type POST_PARAMS_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SITEMAP_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(language) && noindex != true]{    language,    "slug": slug.current,    _updatedAt,    "translations":   *[_type == "translation.metadata" && references(^._id)][0].translations[]{    language,    "slug": value->slug.current,    "noindex": value->noindex  }[defined(slug)]  }
export type SITEMAP_POSTS_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
  _updatedAt: string;
  translations: Array<{
    language: string | null;
    slug: string;
    noindex: boolean | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SIBLINGS_OF_DOC_QUERY
// Query: *[_type == "translation.metadata" && references($id)].translations[]{    language,    "type": value->_type,    "slug": value->slug.current  }
export type SIBLINGS_OF_DOC_QUERY_RESULT = Array<{
  language: string | null;
  type: "page" | "post" | null;
  slug: string | null;
} | null>;

// Source: sanity/lib/queries.ts
// Variable: DOCS_BY_ID_QUERY
// Query: *[_type in ["page", "post"] && _id in $ids]{ _type, language, "slug": slug.current }
export type DOCS_BY_ID_QUERY_RESULT = Array<
  | {
      _type: "page";
      language: string | null;
      slug: string | null;
    }
  | {
      _type: "post";
      language: string | null;
      slug: string | null;
    }
>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug && language == $language][0]{\n    _id,\n    _updatedAt,\n    language,\n    "slug": slug.current,\n    title,\n    description,\n    noindex,\n    "translations": \n  *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n    language,\n    "slug": value->slug.current,\n    "noindex": value->noindex\n  }[defined(slug)]\n,\n    blocks[]{\n      ...,\n      _type == "hero" => { image {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n} },\n      _type == "testimonialGrid" => { testimonials[]{ ..., avatar {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n} } }\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current) && defined(language)]{\n    language,\n    "slug": slug.current\n  }\n': PAGE_PARAMS_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current) && defined(language) && noindex != true]{\n    language,\n    "slug": slug.current,\n    _updatedAt,\n    "translations": \n  *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n    language,\n    "slug": value->slug.current,\n    "noindex": value->noindex\n  }[defined(slug)]\n\n  }\n': SITEMAP_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug && language == $language][0]{\n    _id,\n    _updatedAt,\n    language,\n    "slug": slug.current,\n    title,\n    excerpt,\n    author,\n    publishedAt,\n    tags,\n    noindex,\n    coverImage {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n},\n    body,\n    "translations": \n  *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n    language,\n    "slug": value->slug.current,\n    "noindex": value->noindex\n  }[defined(slug)]\n\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && language == $language && defined(slug.current) && noindex != true]\n    | order(publishedAt desc){\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    author,\n    publishedAt,\n    tags,\n    coverImage {\n  alt,\n  crop,\n  hotspot,\n  asset->{ _id, metadata{ lqip, dimensions{ width, height } } }\n}\n  }\n': POST_INDEX_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && defined(language)]{\n    language,\n    "slug": slug.current\n  }\n': POST_PARAMS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && defined(language) && noindex != true]{\n    language,\n    "slug": slug.current,\n    _updatedAt,\n    "translations": \n  *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n    language,\n    "slug": value->slug.current,\n    "noindex": value->noindex\n  }[defined(slug)]\n\n  }\n': SITEMAP_POSTS_QUERY_RESULT;
    '\n  *[_type == "translation.metadata" && references($id)].translations[]{\n    language,\n    "type": value->_type,\n    "slug": value->slug.current\n  }\n': SIBLINGS_OF_DOC_QUERY_RESULT;
    '\n  *[_type in ["page", "post"] && _id in $ids]{ _type, language, "slug": slug.current }\n': DOCS_BY_ID_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
